server:
    address: localhost
    port: 8989
    contextPath: /SpringMongoDbApp
  
spring:
  application:
    name: SpringMongoDbApp    
  data: 
    mongodb:
      database: dev
      host: localhost
      port: 27017